name: build

on:
  push:
    branches:
      - "*"
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"

      - name: "Install packages and namespace classes with mozart"
        run: composer install

      - name: "Remove development packages"
        run: composer install --no-dev

      - name: "Compile scripts and styles"
        run: |
          npm install 
          npm run production

      - name: "Replace plugin version"
        run: |
          VERSION=$(echo "${GITHUB_SHA}" | head -c8)
          [[ $GITHUB_REF == refs/tags/* ]] && VERSION=${GITHUB_REF#refs/*/}
          [[ $GITHUB_REF == refs/tags/v* ]] && VERSION=${GITHUB_REF#refs/*/v}
          sed -i "s/[0-9]*\.[0-9]*\.[0-9]*\-dev/${VERSION}/g" sitepilot.php

      - name: "Zip plugin files"
        run: |
          mkdir sitepilot
          shopt -s extglob
          mv !(sitepilot|node_modules|.git|.github|deploy.conf) sitepilot
          zip -r ./sitepilot.zip ./sitepilot

      - uses: actions/upload-artifact@v2
        with:
          name: sitepilot
          path: ./sitepilot

      - uses: sitepilot/action-deploy@main
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        with:
          args: rclone copy ./sitepilot.zip remote:files/v1/packages --config="./deploy.conf"
        if: github.event.release

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./sitepilot.zip
          asset_name: sitepilot.zip
          asset_content_type: application/zip
        if: github.event.release
