name: build

on:
  push:
    branches:
      - "*"
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"

      - name: "Install packages and namespace classes with Mozart"
        run: composer install

      - name: "Remove development packages"
        run: composer install --no-dev

      - name: "Compile scripts and styles"
        run: |
          npm install 
          npm run production

      - uses: sitepilot/action-deploy@main
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        with:
          args: /usr/local/bin/deploy plugin remote:files/v1/packages
        #if: github.event.release
